MONGO_DB_DATABASE_NAME: booking-db-dev
MONGO_DB_URI: mongodb://test_user:test_password@localhost:27017/?authMechanism=SCRAM-SHA-256

server:
  port: 8080

spring:
  data:
    mongodb:
      uri: ${MONGO_DB_URI}
      database: ${MONGO_DB_DATABASE_NAME}